version: '3.9'
services:
  brandvx:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./brandvx.db
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_FALLBACK_MODELS=${OPENAI_FALLBACK_MODELS:-gpt-4o-mini}
      - AI_PROVIDER=${AI_PROVIDER:-chat}
      - OPENAI_AGENT_ID=${OPENAI_AGENT_ID:-}
      - OPENAI_AGENTS_URL=${OPENAI_AGENTS_URL:-https://api.openai.com/v1/responses}
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

