name: Deploy Operator UI to Cloudflare Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/operator-ui/**'
      - '!apps/operator-ui/tests-e2e/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/operator-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'apps/operator-ui/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_POSTHOG_KEY: ${{ secrets.VITE_POSTHOG_KEY }}
          VITE_POSTHOG_HOST: ${{ secrets.VITE_POSTHOG_HOST }}
          VITE_FEATURE_SOCIAL: ${{ secrets.VITE_FEATURE_SOCIAL }}
          VITE_BOOKING_URL: ${{ secrets.VITE_BOOKING_URL }}
          VITE_DEV_AUTOCONNECT: ${{ secrets.VITE_DEV_AUTOCONNECT }}
          VITE_DISABLE_MOTION: ${{ secrets.VITE_DISABLE_MOTION }}
          VITE_SHOW_REDIRECT_URIS: ${{ secrets.VITE_SHOW_REDIRECT_URIS }}
          VITE_BETA_RECOMMEND_ONLY: ${{ secrets.VITE_BETA_RECOMMEND_ONLY }}
          VITE_STRIPE_PK: ${{ secrets.VITE_STRIPE_PK }}
          VITE_STRIPE_PRICE_147: ${{ secrets.VITE_STRIPE_PRICE_147 }}
          VITE_STRIPE_PRICE_97: ${{ secrets.VITE_STRIPE_PRICE_97 }}
          VITE_STRIPE_TRIAL_DAYS: ${{ secrets.VITE_STRIPE_TRIAL_DAYS }}
          VITE_STRIPE_BUY_BUTTON_147: ${{ secrets.VITE_STRIPE_BUY_BUTTON_147 }}
          VITE_STRIPE_BUY_BUTTON_97: ${{ secrets.VITE_STRIPE_BUY_BUTTON_97 }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
        run: npm run build

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx --yes wrangler pages deploy dist --project-name=${{ secrets.CF_PAGES_PROJECT }} --branch=main --commit-dirty=true

